FROM ruby:3.1.3-slim

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev libvips git

RUN mkdir /app

COPY . ./app

WORKDIR /app

ARG BUNDLE_ENTERPRISE__CONTRIBSYS__COM

RUN bundle install

ENTRYPOINT [ "/app/docker-dev-entrypoint.sh" ]
