volumes:
  db:
  app:
  bundle:
  
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    tmpfs:
      /app/tmp
    env_file: .env

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true
